#! /bin/bash

#SBATCH -J qwalk           # Job name
#SBATCH -o qwalk.o%j       # Name of stdout output file
#SBATCH -e qwalk.e%j       # Name of stderr error file
#SBATCH -p normal          # Queue name
#SBATCH -N 1               # Total # of nodes
#SBATCH -n 64              # Total # of mpi tasks
#SBATCH -t 08:00:00        # Run time (hh:mm:ss)


ibrun qwalk fe.opt0
ibrun qwalk fe.opt1
ibrun qwalk fe.opt2
ibrun qwalk fe.opt3
ibrun qwalk fe.opt4
ibrun qwalk fe.opt5
