#! /bin/bash

#SBATCH -J qwalk           # Job name
#SBATCH -o qwalk.o%j       # Name of stdout output file
#SBATCH -e qwalk.e%j       # Name of stderr error file
#SBATCH -p normal          # Queue name
#SBATCH -N 1               # Total # of nodes
#SBATCH -n 64              # Total # of mpi tasks
#SBATCH -t 04:00:00        # Run time (hh:mm:ss)


ibrun qwalk o.opt0
ibrun qwalk o.opt1
ibrun qwalk o.opt2
ibrun qwalk o.opt3
ibrun qwalk o.opt4
ibrun qwalk o.opt5
