TACC:  Starting up job 2495811 
TACC:  Starting parallel tasks... 
2018-11-24 14:14:10.577357-06:00
===============
Quantum Package
===============

Git Commit: square determinant coefficients (#242)
Git Date  : Mon Jun 25 02:34:06 2018 -0500
Git SHA1  : f9e473d703adf35bb17000a3e4e5cdc1688b9915


Task server running : tcp://206.76.217.43:41279
 
.. >>>>> [ WALL TIME:        0.000000 s ] [ CPU  TIME:        0.043812 s ] <<<<< ..
 
 Read  n_states
 
.. >>>>> [ WALL TIME:        0.002900 s ] [ CPU  TIME:        0.044597 s ] <<<<< ..
 
 Read  pt2_relative_error
 
.. >>>>> [ WALL TIME:        0.003700 s ] [ CPU  TIME:        0.044743 s ] <<<<< ..
 
 Read  threshold_selectors
 
.. >>>>> [ WALL TIME:        0.004500 s ] [ CPU  TIME:        0.044880 s ] <<<<< ..
 
 Read  n_det_max
 * mo_label          Natural
 
.. >>>>> [ WALL TIME:        0.007300 s ] [ CPU  TIME:        0.045648 s ] <<<<< ..
 
 Read  read_wf
* Number of determinants                                         1
 
.. >>>>> [ WALL TIME:        0.017700 s ] [ CPU  TIME:        0.052964 s ] <<<<< ..
 
 Read  pt2_absolute_error
 
.. >>>>> [ WALL TIME:        0.018600 s ] [ CPU  TIME:        0.053223 s ] <<<<< ..
 
 Read  do_pt2
* Dimension of the psi arrays                               100000
 Read psi_coef           1           1
 
.. >>>>> [ WALL TIME:        0.034100 s ] [ CPU  TIME:        0.055319 s ] <<<<< ..
 
 Read  n_det_max_jacobi
* Number of threads for Diagonalization                          1
 
.. >>>>> [ WALL TIME:        0.036800 s ] [ CPU  TIME:        0.055914 s ] <<<<< ..
 
 Read  threshold_davidson
 
.. >>>>> [ WALL TIME:        0.037600 s ] [ CPU  TIME:        0.056056 s ] <<<<< ..
 
 Read  n_states_diag
 
.. >>>>> [ WALL TIME:        0.040000 s ] [ CPU  TIME:        0.056596 s ] <<<<< ..
 
 Read  ao_num
* mo_tot_num                                                    31
 Read  mo_coef
* N_int                                                          1
 
.. >>>>> [ WALL TIME:        0.057900 s ] [ CPU  TIME:        0.059436 s ] <<<<< ..
 
 Read  elec_beta_num
 
.. >>>>> [ WALL TIME:        0.058700 s ] [ CPU  TIME:        0.059572 s ] <<<<< ..
 
 Read  elec_alpha_num
 Read psi_det
 
.. >>>>> [ WALL TIME:        0.077100 s ] [ CPU  TIME:        0.063371 s ] <<<<< ..
 
 Read  no_vvvv_integrals
 
.. >>>>> [ WALL TIME:        0.078100 s ] [ CPU  TIME:        0.063601 s ] <<<<< ..
 
 Read  disk_access_ao_integrals
 
.. >>>>> [ WALL TIME:        0.078900 s ] [ CPU  TIME:        0.063746 s ] <<<<< ..
 
 Read  disk_access_mo_integrals
 AO map initialized :                 177310
 
.. >>>>> [ WALL TIME:        0.093000 s ] [ CPU  TIME:        0.065211 s ] <<<<< ..
 
 Read  ao_power
 
.. >>>>> [ WALL TIME:        0.105900 s ] [ CPU  TIME:        0.066626 s ] <<<<< ..
 
 Read  ao_prim_num
 
.. >>>>> [ WALL TIME:        0.119100 s ] [ CPU  TIME:        0.068128 s ] <<<<< ..
 
 Read  ao_expo
 
.. >>>>> [ WALL TIME:        0.132200 s ] [ CPU  TIME:        0.069486 s ] <<<<< ..
 
 Read  ao_coef
 
.. >>>>> [ WALL TIME:        0.145600 s ] [ CPU  TIME:        0.071721 s ] <<<<< ..
 
 Read  ao_nucl
 
.. >>>>> [ WALL TIME:        0.146500 s ] [ CPU  TIME:        0.071904 s ] <<<<< ..
 
 Read  ao_integrals_threshold
 Reading the AO integrals
                     0        5029
                     1        5040
                     2        4664
                     3        5211
                     4        3793
                     5        1677
 AO integrals provided
 
 AO -> MO integrals transformation
 ---------------------------------
 
 
.. >>>>> [ WALL TIME:        0.156400 s ] [ CPU  TIME:        0.073478 s ] <<<<< ..
 
 Read  mo_integrals_threshold
 MO map initialized:                 123256
 i
 |+++++++++++++++++++++++++++++++---------------------------------|
 j
 |+++++++++++++++++++++++++++++++---------------------------------|
 k
 |+++++++++++++++++++++++++++++++---------------------------------|
 l
 |+++++++++++++++++++++++++++++++---------------------------------|
 Providing the molecular integrals 
 Buffers :    1.143532     MB / core
 
.. >>>>> [ WALL TIME:        0.158900 s ] [ CPU  TIME:        0.074070 s ] <<<<< ..
 
 Read  nucl_num
 
.. >>>>> [ WALL TIME:        0.172100 s ] [ CPU  TIME:        0.075274 s ] <<<<< ..
 
 Read  nucl_label
 
.. >>>>> [ WALL TIME:        0.184900 s ] [ CPU  TIME:        0.076496 s ] <<<<< ..
 
 Read  nucl_charge
 
.. >>>>> [ WALL TIME:        0.198000 s ] [ CPU  TIME:        0.077807 s ] <<<<< ..
 

Nuclear Coordinates (Angstroms)
===============================

================ ============ ============ ============ ============
      Atom          Charge          X            Y            Z 
================ ============ ============ ============ ============
Fe                  16.000000     0.000000     0.000000     0.000000
================ ============ ============ ============ ============

   2.941176     % in    1.74259999999776      s  2.479553222656250E-004 MB
 Molecular integrals provided:
  Size of MO map             0.839309692382812      MB
  Number of MO integrals:                  44106
  cpu  time :   1.74904900000000      s
  wall time :   1.78999999999360      s  ( x   0.977122346372210      )
 Molecular integrals provided
 
.. >>>>> [ WALL TIME:        2.041400 s ] [ CPU  TIME:        1.916415 s ] <<<<< ..
 
 Read  disk_access_mo_one_integrals
 
.. >>>>> [ WALL TIME:        2.042100 s ] [ CPU  TIME:        1.916593 s ] <<<<< ..
 
 Read  disk_access_ao_one_integrals
 
.. >>>>> [ WALL TIME:        2.152000 s ] [ CPU  TIME:        2.021985 s ] <<<<< ..
 
 Read  do_pseudo
 Providing the mono electronic integrals
 
.. >>>>> [ WALL TIME:        2.156900 s ] [ CPU  TIME:        2.025466 s ] <<<<< ..
 
 Read  pseudo_kmax
 
.. >>>>> [ WALL TIME:        2.158500 s ] [ CPU  TIME:        2.025754 s ] <<<<< ..
 
 Read  pseudo_klocmax
 
.. >>>>> [ WALL TIME:        2.173900 s ] [ CPU  TIME:        2.027368 s ] <<<<< ..
 
 Read  pseudo_n_k
 
.. >>>>> [ WALL TIME:        2.189100 s ] [ CPU  TIME:        2.029259 s ] <<<<< ..
 
 Read  pseudo_dz_k
 
.. >>>>> [ WALL TIME:        2.203400 s ] [ CPU  TIME:        2.030810 s ] <<<<< ..
 
 Read  pseudo_v_k
 Providing the nuclear electron pseudo integrals (local)
 
.. >>>>> [ WALL TIME:        2.227600 s ] [ CPU  TIME:        2.053227 s ] <<<<< ..
 
 Read  pseudo_lmax
 
.. >>>>> [ WALL TIME:        2.242500 s ] [ CPU  TIME:        2.054711 s ] <<<<< ..
 
 Read  pseudo_v_kl
 
.. >>>>> [ WALL TIME:        2.256800 s ] [ CPU  TIME:        2.056391 s ] <<<<< ..
 
 Read  pseudo_n_kl
 
.. >>>>> [ WALL TIME:        2.271700 s ] [ CPU  TIME:        2.058135 s ] <<<<< ..
 
 Read  pseudo_dz_kl
 Providing the nuclear electron pseudo integrals (non-local)
 
.. >>>>> [ WALL TIME:        2.406500 s ] [ CPU  TIME:        2.191863 s ] <<<<< ..
 
 Read  s2_eig
 
.. >>>>> [ WALL TIME:        2.410000 s ] [ CPU  TIME:        2.192646 s ] <<<<< ..
 
 Read  disk_access_nuclear_repulsion
 
.. >>>>> [ WALL TIME:        2.410000 s ] [ CPU  TIME:        2.192665 s ] <<<<< ..
 
* Nuclear repulsion energy                           0.000000000000000    
 
.. >>>>> [ WALL TIME:        2.410000 s ] [ CPU  TIME:        2.192681 s ] <<<<< ..
 
* Energy of state    1                              -122.5640291887292    
* S^2 of state    1                                  6.000000000000000    
 
.. >>>>> [ WALL TIME:        2.410800 s ] [ CPU  TIME:        2.192953 s ] <<<<< ..
 
 Read  threshold_generators
 
.. >>>>> [ WALL TIME:        2.410900 s ] [ CPU  TIME:        2.193000 s ] <<<<< ..
 
* Energy of state    1                              -122.5640291887292    
* S^2 of state    1                                  6.000000000000000    
* Saved determinants                                             1
 
.. >>>>> [ WALL TIME:        2.532000 s ] [ CPU  TIME:        2.210108 s ] <<<<< ..
 
 Read  correlation_energy_ratio_max
 
.. >>>>> [ WALL TIME:        2.532800 s ] [ CPU  TIME:        2.210371 s ] <<<<< ..
 
 Read  pt2_max
--------------------------------------------------------------------------------
 
.. >>>>> [ WALL TIME:        2.532900 s ] [ CPU  TIME:        2.210439 s ] <<<<< ..
 
* Number of generators                                           1
* N_generators_bitmask                                           1
* N_generators_bitmask_restart                                   1
* N_cas_bitmask                                                  1
 Read CAS bitmask
* Number of inactive MOs                                        10
* Number of virtual MOs                                         10
* Number of core MOs                                             0
 
.. >>>>> [ WALL TIME:        2.538400 s ] [ CPU  TIME:        2.211820 s ] <<<<< ..
 
 Read  distributed_davidson
* PT2 Energy denominator                            -122.5640291887292    
 
.. >>>>> [ WALL TIME:        2.542200 s ] [ CPU  TIME:        2.214751 s ] <<<<< ..
 
* Number of selectors                                            1
50.00 %  in             11.9104ms, ~           11.9104ms left
                                                                            
Summary at N_det =            1
-----------------------------------
 
* Correlation ratio                                  0.000000000000000    
 
# ============ =============================
                    State      1
# ============ =============================
# E           -122.56402919
# PT2           -0.53900997     0.00000000
#
# E+PT2       -123.10303916     0.00000000
# ============ =============================
 
 N_det             =            1
 N_states          =            1
 correlation_ratio =   0.000000000000000E+000
 State            1
 PT2             =  -0.539009970224091     
 E               =   -122.564029188729     
 E+PT2           =   -123.103039158953       +/-   0.000000000000000E+000
 -----
 
.. >>>>> [ WALL TIME:        2.646200 s ] [ CPU  TIME:        2.329193 s ] <<<<< ..
 
* Number of generators                                           1
 
.. >>>>> [ WALL TIME:        2.648600 s ] [ CPU  TIME:        2.332918 s ] <<<<< ..
 
* Number of selectors                                            1
50.00 %  in             6.53887ms, ~           6.53887ms left
                                                                            
.. >>>>> [ WALL TIME:        2.654000 s ] [ CPU  TIME:        2.339163 s ] <<<<< ..
 
* Number of generators                                           1
* Number of occupation patterns                                  2
 Added determinants for S^2
 
.. >>>>> [ WALL TIME:        2.654100 s ] [ CPU  TIME:        2.339307 s ] <<<<< ..
 
 
.. >>>>> [ WALL TIME:        2.654100 s ] [ CPU  TIME:        2.339379 s ] <<<<< ..
 
* Number of generators                                           1
* Saved determinants                                             2
 
.. >>>>> [ WALL TIME:        2.752800 s ] [ CPU  TIME:        2.448884 s ] <<<<< ..
 
* Energy of state    1                              -122.5769016545905    
* S^2 of state    1                                  6.000000000000000    
* Saved determinants                                             2
--------------------------------------------------------------------------------
 
.. >>>>> [ WALL TIME:        2.861900 s ] [ CPU  TIME:        2.555871 s ] <<<<< ..
 
* Number of generators                                           2
* PT2 Energy denominator                            -122.5769016545905    
 
.. >>>>> [ WALL TIME:        2.865400 s ] [ CPU  TIME:        2.557339 s ] <<<<< ..
 
* Number of selectors                                            2
33.33 %  in             7.49707ms, ~           14.9941ms left
                                                                            
Summary at N_det =            2
-----------------------------------
 
* Correlation ratio                                 0.2499045230235550E-01
 
# ============ =============================
                    State      1
# ============ =============================
# E           -122.57690165
# PT2           -0.50222289     0.00000000
#
# E+PT2       -123.07912454     0.00000000
# ============ =============================
 
 N_det             =            2
 N_states          =            1
 correlation_ratio =   2.499045230235550E-002
 State            1
 PT2             =  -0.502222887578672     
 E               =   -122.576901654591     
 E+PT2           =   -123.079124542169       +/-   0.000000000000000E+000
 -----
 
.. >>>>> [ WALL TIME:        2.998300 s ] [ CPU  TIME:        2.702730 s ] <<<<< ..
 
* Number of generators                                           1
 
.. >>>>> [ WALL TIME:        3.001100 s ] [ CPU  TIME:        2.706758 s ] <<<<< ..
 
* Number of selectors                                            2
50.00 %  in             6.75106ms, ~           6.75106ms left
                                                                            
.. >>>>> [ WALL TIME:        3.006200 s ] [ CPU  TIME:        2.712479 s ] <<<<< ..
 
* Number of generators                                           1
* Number of occupation patterns                                  4
 Added determinants for S^2
 
.. >>>>> [ WALL TIME:        3.006300 s ] [ CPU  TIME:        2.712607 s ] <<<<< ..
 
 
.. >>>>> [ WALL TIME:        3.006300 s ] [ CPU  TIME:        2.712680 s ] <<<<< ..
 
* Number of generators                                           1
* Saved determinants                                             9
 
.. >>>>> [ WALL TIME:        3.105400 s ] [ CPU  TIME:        2.822752 s ] <<<<< ..
 
* Energy of state    1                              -122.6032283683944    
* S^2 of state    1                                  6.000000000000000    
* Saved determinants                                             9
--------------------------------------------------------------------------------
 
.. >>>>> [ WALL TIME:        3.213200 s ] [ CPU  TIME:        2.929718 s ] <<<<< ..
 
* Number of generators                                           9
* PT2 Energy denominator                            -122.6032283683944    
 
.. >>>>> [ WALL TIME:        3.216400 s ] [ CPU  TIME:        2.931400 s ] <<<<< ..
 
* Number of selectors                                            9
10.00 %  in             8.05044ms, ~            72.454ms left
                                                                            
Summary at N_det =            9
-----------------------------------
 
* Correlation ratio                                 0.8339565974162257E-01
 
# ============ =============================
                    State      1
# ============ =============================
# E           -122.60322837
# PT2           -0.43083943     0.00000000
#
# E+PT2       -123.03406779     0.00000000
# ============ =============================
 
 N_det             =            9
 N_states          =            1
 correlation_ratio =   8.339565974162257E-002
 State            1
 PT2             =  -0.430839426500288     
 E               =   -122.603228368394     
 E+PT2           =   -123.034067794895       +/-   0.000000000000000E+000
 -----

Extrapolated energies
------------------------

 
 State            1
 
 =========== ===================
 minimum PT2 Extrapolated energy
 =========== ===================
    -0.5022       -122.76212493
    -0.5390       -122.75963336
 =========== ===================
 
 
.. >>>>> [ WALL TIME:        3.374100 s ] [ CPU  TIME:        3.099214 s ] <<<<< ..
 
* Number of generators                                           2
 
.. >>>>> [ WALL TIME:        3.377200 s ] [ CPU  TIME:        3.103455 s ] <<<<< ..
 
* Number of selectors                                            5
33.33 %  in             7.46155ms, ~           14.9231ms left
                                                                            
.. >>>>> [ WALL TIME:        3.386000 s ] [ CPU  TIME:        3.112703 s ] <<<<< ..
 
* Number of generators                                           2
* Number of occupation patterns                                  8
 Added determinants for S^2
 
.. >>>>> [ WALL TIME:        3.386100 s ] [ CPU  TIME:        3.112889 s ] <<<<< ..
 
 
.. >>>>> [ WALL TIME:        3.386100 s ] [ CPU  TIME:        3.112973 s ] <<<<< ..
 
* Number of generators                                           2
* Saved determinants                                            33
 
.. >>>>> [ WALL TIME:        3.525400 s ] [ CPU  TIME:        3.262445 s ] <<<<< ..
 
* Energy of state    1                              -122.6465558632950    
* S^2 of state    1                                  6.000000000000002    
* Saved determinants                                            33
--------------------------------------------------------------------------------
 
.. >>>>> [ WALL TIME:        3.640500 s ] [ CPU  TIME:        3.331168 s ] <<<<< ..
 
* Number of generators                                          33
* Size of deterministic set                                      1
* PT2 Energy denominator                            -122.6465558632949    
 
.. >>>>> [ WALL TIME:        3.640700 s ] [ CPU  TIME:        3.331363 s ] <<<<< ..
 
* Number of selectors                                           33
 
.. >>>>> [ WALL TIME:        3.641100 s ] [ CPU  TIME:        3.331815 s ] <<<<< ..
 
* Number of generators                                          33
* Size of deterministic set                                      1
 
.. >>>>> [ WALL TIME:        3.641200 s ] [ CPU  TIME:        3.331834 s ] <<<<< ..
 
* Number of selectors                                           33
 ========== ================= ================= =================
  Samples        Energy         Stat. Error         Seconds      
 ========== ================= ================= =================
 0.43 %  in             4.09245ms, ~           945.357ms left
  19.0       -122.9865691445         0.156E-04            0.1815                    
                                                                            ========== ================= ================= =================
 
.. >>>>> [ WALL TIME:        3.828800 s ] [ CPU  TIME:        3.503235 s ] <<<<< ..
 
* Number of generators                                          33
* Size of deterministic set                                      1
 
.. >>>>> [ WALL TIME:        3.828900 s ] [ CPU  TIME:        3.503358 s ] <<<<< ..
 
* Number of selectors                                           33
 
Summary at N_det =           33
-----------------------------------
 
* Correlation ratio                                 0.1953109367358529    
 
# ============ =============================
                    State      1
# ============ =============================
# E           -122.64655586
# PT2           -0.34001328     0.00001555
#
# E+PT2       -122.98656914     0.00001555
# ============ =============================
 
 N_det             =           33
 N_states          =            1
 correlation_ratio =   0.195310936735853     
 State            1
 PT2             =  -0.340013281184068     
 E               =   -122.646555863295     
 E+PT2           =   -122.986569144479       +/-   1.555391581957128E-005
 -----

Extrapolated energies
------------------------

 
 State            1
 
 =========== ===================
 minimum PT2 Extrapolated energy
 =========== ===================
    -0.4308       -122.80875501
    -0.5022       -122.79201854
    -0.5390       -122.78539035
 =========== ===================
 
 
.. >>>>> [ WALL TIME:        3.954300 s ] [ CPU  TIME:        3.642060 s ] <<<<< ..
 
* Number of generators                                           7
 
.. >>>>> [ WALL TIME:        3.957500 s ] [ CPU  TIME:        3.646865 s ] <<<<< ..
 
* Number of selectors                                           13
12.50 %  in             8.99839ms, ~           62.9888ms left
                                                                            
.. >>>>> [ WALL TIME:        3.988200 s ] [ CPU  TIME:        3.676734 s ] <<<<< ..
 
* Number of generators                                           7
* Number of occupation patterns                                 20
 Added determinants for S^2
 
.. >>>>> [ WALL TIME:        3.988500 s ] [ CPU  TIME:        3.677379 s ] <<<<< ..
 
 
.. >>>>> [ WALL TIME:        3.988600 s ] [ CPU  TIME:        3.677469 s ] <<<<< ..
 
* Number of generators                                           7
* Saved determinants                                           178
 
.. >>>>> [ WALL TIME:        4.101300 s ] [ CPU  TIME:        3.811079 s ] <<<<< ..
 
* Energy of state    1                              -122.7071798702002    
* S^2 of state    1                                  6.000000000000001    
* Saved determinants                                           178
--------------------------------------------------------------------------------
 
.. >>>>> [ WALL TIME:        4.206600 s ] [ CPU  TIME:        3.904052 s ] <<<<< ..
 
* Number of generators                                         178
* Size of deterministic set                                      1
* PT2 Energy denominator                            -122.7071798702002    
 
.. >>>>> [ WALL TIME:        4.207300 s ] [ CPU  TIME:        3.904740 s ] <<<<< ..
 
* Number of selectors                                          178
 
.. >>>>> [ WALL TIME:        4.207700 s ] [ CPU  TIME:        3.905114 s ] <<<<< ..
 
* Number of generators                                         178
* Size of deterministic set                                      1
 
.. >>>>> [ WALL TIME:        4.207700 s ] [ CPU  TIME:        3.905133 s ] <<<<< ..
 
* Number of selectors                                          178
 ========== ================= ================= =================
  Samples        Energy         Stat. Error         Seconds      
 ========== ================= ================= =================
 0.27 %  in             4.11749ms, ~            1.54818s left
  127.       -122.9458200977         0.143E-04            0.6600                    
                                                                            ========== ================= ================= =================
 
.. >>>>> [ WALL TIME:        4.871600 s ] [ CPU  TIME:        4.541154 s ] <<<<< ..
 
* Number of generators                                         178
* Size of deterministic set                                      1
 
.. >>>>> [ WALL TIME:        4.871700 s ] [ CPU  TIME:        4.541223 s ] <<<<< ..
 
* Number of selectors                                          178
 
Summary at N_det =          178
-----------------------------------
 
* Correlation ratio                                 0.3749452333542551    
 
# ============ =============================
                    State      1
# ============ =============================
# E           -122.70717987
# PT2           -0.23864023     0.00001428
#
# E+PT2       -122.94582010     0.00001428
# ============ =============================
 
 N_det             =          178
 N_states          =            1
 correlation_ratio =   0.374945233354255     
 State            1
 PT2             =  -0.238640227538256     
 E               =   -122.707179870200     
 E+PT2           =   -122.945820097738       +/-   1.427553770268414E-005
 -----

Extrapolated energies
------------------------

 
 State            1
 
 =========== ===================
 minimum PT2 Extrapolated energy
 =========== ===================
    -0.3400       -122.84989360
    -0.4308       -122.83468797
    -0.5022       -122.82098631
    -0.5390       -122.81382156
 =========== ===================
 
 
.. >>>>> [ WALL TIME:        5.507800 s ] [ CPU  TIME:        4.753139 s ] <<<<< ..
 
* Number of generators                                          17
 
.. >>>>> [ WALL TIME:        5.510600 s ] [ CPU  TIME:        4.754472 s ] <<<<< ..
 
* Number of selectors                                           42
 5.56 %  in             11.3201ms, ~           192.442ms left
                                                                            
.. >>>>> [ WALL TIME:        5.585400 s ] [ CPU  TIME:        4.825886 s ] <<<<< ..
 
* Number of generators                                          17
* Number of occupation patterns                                 75
 Added determinants for S^2
 
.. >>>>> [ WALL TIME:        5.586300 s ] [ CPU  TIME:        4.827509 s ] <<<<< ..
 
 
.. >>>>> [ WALL TIME:        5.586300 s ] [ CPU  TIME:        4.827624 s ] <<<<< ..
 
* Number of generators                                          17
* Saved determinants                                           637
 
.. >>>>> [ WALL TIME:        5.782200 s ] [ CPU  TIME:        5.127605 s ] <<<<< ..
 
* Energy of state    1                              -122.7850298829374    
* S^2 of state    1                                  6.000000000000001    
* Saved determinants                                           637
--------------------------------------------------------------------------------
 
.. >>>>> [ WALL TIME:        5.900600 s ] [ CPU  TIME:        5.145218 s ] <<<<< ..
 
* Number of generators                                         635
* Size of deterministic set                                      1
* PT2 Energy denominator                            -122.7850298829370    
 
.. >>>>> [ WALL TIME:        5.903200 s ] [ CPU  TIME:        5.147759 s ] <<<<< ..
 
* Number of selectors                                          637
 
.. >>>>> [ WALL TIME:        5.903600 s ] [ CPU  TIME:        5.148201 s ] <<<<< ..
 
* Number of generators                                         635
* Size of deterministic set                                      1
 
.. >>>>> [ WALL TIME:        5.903600 s ] [ CPU  TIME:        5.148228 s ] <<<<< ..
 
* Number of selectors                                          637
 ========== ================= ================= =================
  Samples        Energy         Stat. Error         Seconds      
 ========== ================= ================= =================
 0.12 %  in             4.96364ms, ~            4.13471s left
77.22 %  in              2.01678s, ~           595.012ms left
  465.       -122.9234526053         0.124E-04            2.4839                    
                                                                            ========== ================= ================= =================
 
.. >>>>> [ WALL TIME:        8.393400 s ] [ CPU  TIME:        7.603166 s ] <<<<< ..
 
* Number of generators                                         635
* Size of deterministic set                                      1
 
.. >>>>> [ WALL TIME:        8.393400 s ] [ CPU  TIME:        7.603328 s ] <<<<< ..
 
* Number of selectors                                          637
 
Summary at N_det =          637
-----------------------------------
 
* Correlation ratio                                 0.6148756146786616    
 
# ============ =============================
                    State      1
# ============ =============================
# E           -122.78502988
# PT2           -0.13842272     0.00001245
#
# E+PT2       -122.92345261     0.00001245
# ============ =============================
 
 N_det             =          637
 N_states          =            1
 correlation_ratio =   0.614875614678662     
 State            1
 PT2             =  -0.138422722385891     
 E               =   -122.785029882937     
 E+PT2           =   -122.923452605323       +/-   1.244840407927698E-005
 -----

Extrapolated energies
------------------------

 
 State            1
 
 =========== ===================
 minimum PT2 Extrapolated energy
 =========== ===================
    -0.2386       -122.89255811
    -0.3400       -122.87706934
    -0.4308       -122.86359346
    -0.5022       -122.85188384
    -0.5390       -122.84497416
 =========== ===================
 
 
.. >>>>> [ WALL TIME:        8.571100 s ] [ CPU  TIME:        7.795549 s ] <<<<< ..
 
* Number of generators                                          53
 
.. >>>>> [ WALL TIME:        8.574100 s ] [ CPU  TIME:        7.800221 s ] <<<<< ..
 
* Number of selectors                                          150
 1.85 %  in             23.7875ms, ~            1.26074s left
                                                                            
.. >>>>> [ WALL TIME:        8.857800 s ] [ CPU  TIME:        8.071723 s ] <<<<< ..
 
* Number of generators                                          53
* Number of occupation patterns                                263
 Added determinants for S^2
 
.. >>>>> [ WALL TIME:        8.860700 s ] [ CPU  TIME:        8.077548 s ] <<<<< ..
 
 
.. >>>>> [ WALL TIME:        8.860800 s ] [ CPU  TIME:        8.077820 s ] <<<<< ..
 
* Number of generators                                          53
* Saved determinants                                          2480
 
.. >>>>> [ WALL TIME:        8.965000 s ] [ CPU  TIME:        8.196582 s ] <<<<< ..
 
 Read  davidson_sze_max
 
.. >>>>> [ WALL TIME:        8.966800 s ] [ CPU  TIME:        8.199384 s ] <<<<< ..
 
 Read  state_following
 
.. >>>>> [ WALL TIME:        8.968500 s ] [ CPU  TIME:        8.202841 s ] <<<<< ..
 

Davidson Diagonalization
------------------------

* Number of states                                               1
* Number of states in diagonalization                            4
* Number of determinants                                      2480
* Memory(Gb)                                        0.2442598342895508E-02

===== ================ =========== =========== 
Iter       Energy          S^2       Residual  
===== ================ =========== =========== 
   1   -122.7851232558    6.000024   0.120E-01
   2   -122.8443064306    6.000010   0.591E-03
   3   -122.8456890982    6.000004   0.140E-03
   4   -122.8458513295    6.000001   0.694E-05
   5   -122.8458732389    6.000000   0.387E-06
   6   -122.8458750386    6.000000   0.897E-07
   7   -122.8458752133    6.000000   0.876E-08
   1   -122.8458752133    6.000000   0.271E-08
   2   -122.8458752216    6.000000   0.233E-09
   3   -122.8458752222    6.000000   0.118E-10
====== ================ =========== ===========

 
.. >>>>> [ WALL TIME:        9.110200 s ] [ CPU  TIME:        8.425592 s ] <<<<< ..
 
 
.. >>>>> [ WALL TIME:        9.110200 s ] [ CPU  TIME:        8.425613 s ] <<<<< ..
 
* Energy of state    1                              -122.8458752222207    
* S^2 of state    1                                  6.000000000008256    
* Saved determinants                                          2480
--------------------------------------------------------------------------------
 
.. >>>>> [ WALL TIME:        9.237900 s ] [ CPU  TIME:        8.446851 s ] <<<<< ..
 
* Number of generators                                        2471
* Size of deterministic set                                    256
* PT2 Energy denominator                            -122.8458752222207    
 
.. >>>>> [ WALL TIME:        9.253400 s ] [ CPU  TIME:        8.462364 s ] <<<<< ..
 
* Number of selectors                                         2480
 
.. >>>>> [ WALL TIME:        9.254000 s ] [ CPU  TIME:        8.462881 s ] <<<<< ..
 
* Number of generators                                        2471
* Size of deterministic set                                    256
 
.. >>>>> [ WALL TIME:        9.254000 s ] [ CPU  TIME:        8.462965 s ] <<<<< ..
 
* Number of selectors                                         2480
 ========== ================= ================= =================
  Samples        Energy         Stat. Error         Seconds      
 ========== ================= ================= =================
 0.00 %  in             44.3547ms, ~            20.6353m left
14.24 %  in              2.05025s, ~            12.3479s left
30.00 %  in              4.05258s, ~            9.45522s left
80.60 %  in               6.0575s, ~            1.45784s left
96.63 %  in              8.08585s, ~           281.768ms left
 0.171E+04   -122.9114708436         0.194E-05            8.6483                    
                                                                            ========== ================= ================= =================
 
.. >>>>> [ WALL TIME:       17.945400 s ] [ CPU  TIME:       17.023382 s ] <<<<< ..
 
* Number of generators                                        2471
* Size of deterministic set                                    256
 
.. >>>>> [ WALL TIME:       17.945500 s ] [ CPU  TIME:       17.023605 s ] <<<<< ..
 
* Number of selectors                                         2480
 
Summary at N_det =         2480
-----------------------------------
 
* Correlation ratio                                 0.8112039230727475    
 
# ============ =============================
                    State      1
# ============ =============================
# E           -122.84587522
# PT2           -0.06559562     0.00000194
#
# E+PT2       -122.91147084     0.00000194
# ============ =============================
 
 N_det             =         2480
 N_states          =            1
 correlation_ratio =   0.811203923072747     
 State            1
 PT2             =  -6.559562140570159E-002
 E               =   -122.845875222221     
 E+PT2           =   -122.911470843626       +/-   1.935972499619396E-006
 -----

Extrapolated energies
------------------------

 
 State            1
 
 =========== ===================
 minimum PT2 Extrapolated energy
 =========== ===================
    -0.1384       -122.90067883
    -0.2386       -122.89740456
    -0.3400       -122.88875510
    -0.4308       -122.87953380
    -0.5022       -122.87091673
    -0.5390       -122.86539000
 =========== ===================
 
 
.. >>>>> [ WALL TIME:       18.075900 s ] [ CPU  TIME:       17.168465 s ] <<<<< ..
 
* Number of generators                                         157
 
.. >>>>> [ WALL TIME:       18.078700 s ] [ CPU  TIME:       17.172928 s ] <<<<< ..
 
* Number of selectors                                          533
 0.63 %  in             21.5373ms, ~            3.38136s left
                                                                            
.. >>>>> [ WALL TIME:       19.394600 s ] [ CPU  TIME:       17.685373 s ] <<<<< ..
 
* Number of generators                                         157
* Number of occupation patterns                                865
 Added determinants for S^2
 
.. >>>>> [ WALL TIME:       19.409100 s ] [ CPU  TIME:       17.699824 s ] <<<<< ..
 
 
.. >>>>> [ WALL TIME:       19.409500 s ] [ CPU  TIME:       17.700284 s ] <<<<< ..
 
* Number of generators                                         157
* Saved determinants                                         10436
 
.. >>>>> [ WALL TIME:       19.557100 s ] [ CPU  TIME:       17.739084 s ] <<<<< ..
 

Davidson Diagonalization
------------------------

* Number of states                                               1
* Number of states in diagonalization                            4
* Number of determinants                                     10436
* Memory(Gb)                                        0.9815633296966553E-02

===== ================ =========== =========== 
Iter       Energy          S^2       Residual  
===== ================ =========== =========== 
   1   -122.8458788089    6.000001   0.690E-02
   2   -122.8788586628    6.000005   0.705E-03
   3   -122.8809408164    6.000012   0.166E-03
   4   -122.8814504793    6.000007   0.134E-03
   5   -122.8816438870    6.000003   0.102E-03
   6   -122.8816928535    6.000001   0.207E-04
   7   -122.8817221396    6.000001   0.164E-05
   1   -122.8817221396    6.000001   0.162E-05
   2   -122.8817278916    6.000000   0.679E-06
   3   -122.8817296468    6.000000   0.153E-06
   4   -122.8817299998    6.000000   0.197E-07
   5   -122.8817300624    6.000000   0.246E-08
   6   -122.8817300704    6.000000   0.561E-09
   7   -122.8817300726    6.000000   0.136E-09
   1   -122.8817300726    6.000000   0.136E-09
   2   -122.8817300731    6.000000   0.540E-10
====== ================ =========== ===========

 
.. >>>>> [ WALL TIME:       21.354800 s ] [ CPU  TIME:       19.533112 s ] <<<<< ..
 
 
.. >>>>> [ WALL TIME:       21.354900 s ] [ CPU  TIME:       19.533153 s ] <<<<< ..
 
* Energy of state    1                              -122.8817300730704    
* S^2 of state    1                                  6.000000000027795    
* Saved determinants                                         10436
 
.. >>>>> [ WALL TIME:       21.541800 s ] [ CPU  TIME:       19.568122 s ] <<<<< ..
 
* Number of generators                                       10436
* Size of deterministic set                                    106
* PT2 Energy denominator                            -122.8817300730705    
 
.. >>>>> [ WALL TIME:       21.658400 s ] [ CPU  TIME:       19.684515 s ] <<<<< ..
 
* Number of selectors                                        10436
 
.. >>>>> [ WALL TIME:       21.659800 s ] [ CPU  TIME:       19.685830 s ] <<<<< ..
 
* Number of generators                                       10436
* Size of deterministic set                                    106
 
.. >>>>> [ WALL TIME:       21.659900 s ] [ CPU  TIME:       19.685997 s ] <<<<< ..
 
* Number of selectors                                        10436
 ========== ================= ================= =================
  Samples        Energy         Stat. Error         Seconds      
 ========== ================= ================= =================
 0.00 %  in             41.9695ms, ~            14.7096m left
25.23 %  in              2.04222s, ~            6.05352s left
50.68 %  in               4.2836s, ~            4.16786s left
52.79 %  in              6.28879s, ~            5.62485s left
56.76 %  in              8.77782s, ~            6.68779s left
  167.       -122.9098938423         0.259E-05           10.0241                    
  316.       -122.9098909309         0.979E-06           10.5794                    
                                                                            ========== ================= ================= =================
 
.. >>>>> [ WALL TIME:       32.282800 s ] [ CPU  TIME:       30.026409 s ] <<<<< ..
 
* Number of generators                                       10436
* Size of deterministic set                                    106
 
.. >>>>> [ WALL TIME:       32.283000 s ] [ CPU  TIME:       30.026632 s ] <<<<< ..
 
* Number of selectors                                        10436
 N_det             =        10436
 N_states          =            1
 correlation_ratio =   0.811203923072747     

Extrapolated energies
------------------------

 
 State            1
 
 =========== ===================
 minimum PT2 Extrapolated energy
 =========== ===================
    -0.0656       -122.90870242
    -0.1384       -122.90497998
    -0.2386       -122.90191954
    -0.3400       -122.89594471
    -0.4308       -122.88922055
    -0.5022       -122.88270876
    -0.5390       -122.87833864
 =========== ===================
 
 
Summary at N_det =        10436
-----------------------------------
 
* Correlation ratio                                 0.8112039230727475    
 
 
# ============ =============================
                    State      1
# ============ =============================
# E           -122.88173007
# PT2           -0.02816086     0.00000098
#
# E+PT2       -122.90989093     0.00000098
# ============ =============================
 
Wall time : 34.001s

TACC:  Shutdown complete. Exiting. 
